youtube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtubeapp.urls')),

]

youtubeapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name='ytproject'

urlpatterns = [
    path('', views.index, name='home'),
    path('download/', views.download, name='download'),
    path('download/<resolution>/', views.yt_download_done, name='download_done'),
]

youtubeapp/models.py
from django.db import models

# Create your models here.

youtubeapp/views.py
from django.shortcuts import render
from pytube import YouTube
from django.http import FileResponse

import os
# Create your views here.

def index(request):
    return render(request, 'index.html')

def download(request):
    global url
    url = request.GET.get('url')
    yt = YouTube(url)
    video = []
    video = yt.streams.filter(progressive=True).all()
    embed_link = url.replace("watch?v=", "embed/")
    Title = yt.title
    context = {'video': video, 'embed': embed_link, 'title': Title}
    return render(request, 'download.html', context)

def yt_download_done(request, resolution):
    global url
    homedir = os.path.expanduser("~")
    dirs = ''
    if request.method == "POST":
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, 'done.html')
    else:
        return render(request, 'error.html')

youtubeapp/templates/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DONE</title>
</head>
<body>
DONE
</body>
</html>

youtubeapp/templates/download.html
<!--Navbar starts here-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Download from Youtube</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Facebook Photo/Video Download <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Instagram Photo/Video Download</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="#">Whatsapp Status Download</a>
      </li>

    </ul>
  </div>
</nav>

<!--Navbar ends here-->

<div class="container">
    <h1>{{title}}</h1>
<div class="my-5 embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src={{embed}} allowfullscreen></iframe>
</div>

    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Size</th>
      <th scope="col">Quality</th>
      <th scope="col">Type</th>
           <th scope="col">Download</th>
    </tr>
  </thead>
    {% for j in video %}
  <tbody>
    <tr>
      <td>{{j.filesize}}</td>
            <td>{{j.resolution}}</td>
           <td>{{j.type}}</td>
        <td>

          <form action="{% url 'ytproject:download_done' j.resolution %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-success" value="Download">

          </form>


        </td>
    </tr>
     </tbody>
    {% endfor %}
</table>

</div>



<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

youtubeapp/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
Error
</body>
</html>

youtubeapp/templates/index.html
<!--Navbar starts here-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Download from Youtube</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Facebook Photo/Video Download <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Instagram Photo/Video Download</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="#">Whatsapp Status Download</a>
      </li>

    </ul>
  </div>
</nav>

<!--Navbar ends here-->

<div class="container">
<br> <br>
    <h1> Enter youtube link here </h1>
<!--form start here-->
<form action="download/" method="GET">
  <div class="form-group">
    <input name="url" type="text" class="form-control" id="text" aria-describedby="emailHelp" placeholder="Enter your Selected Youtube Link">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<!--form end here-->

</div>



<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>